cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP076.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP076-BiooBarcode_30_CACCGG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP076-BiooBarcode_30_CACCGG_R2.fastq.gz 
 > $LOGDIR/KP076_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB012.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB012-BiooBarcode_31_CACGAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB012-BiooBarcode_31_CACGAT_R1.fastq.gz 
 > $LOGDIR/BB012_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP014.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP014-BiooBarcode_22_CGTACG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP014-BiooBarcode_22_CGTACG_R1.fastq.gz 
 > $LOGDIR/KP014_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP017.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP017-BiooBarcode_23_GAGTGG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP017-BiooBarcode_23_GAGTGG_R1.fastq.gz 
 > $LOGDIR/KP017_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM118.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM118-BiooBarcode15_ATGTCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM118-BiooBarcode15_ATGTCA_R1.fastq.gz 
 > $LOGDIR/OM118_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM236.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM236-BiooBarcode21_GTTTCG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM236-BiooBarcode21_GTTTCG_R2.fastq.gz 
 > $LOGDIR/OM236_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB017.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB017-BiooBarcode_34_CATGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB017-BiooBarcode_34_CATGGC_R2.fastq.gz 
 > $LOGDIR/BB017_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM018.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM018-BiooBarcode6_CTTGTA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM018-BiooBarcode6_CTTGTA_R2.fastq.gz 
 > $LOGDIR/OM018_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP034.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP034-BiooBarcode_24_GGTAGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP034-BiooBarcode_24_GGTAGC_R2.fastq.gz 
 > $LOGDIR/KP034_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP076.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP076-BiooBarcode_30_CACCGG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP076-BiooBarcode_30_CACCGG_R2.fastq.gz > $LOGDIR/KP076_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB012.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB012-BiooBarcode_31_CACGAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB012-BiooBarcode_31_CACGAT_R1.fastq.gz > $LOGDIR/BB012_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP014.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP014-BiooBarcode_22_CGTACG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP014-BiooBarcode_22_CGTACG_R1.fastq.gz > $LOGDIR/KP014_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP017.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP017-BiooBarcode_23_GAGTGG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP017-BiooBarcode_23_GAGTGG_R1.fastq.gz > $LOGDIR/KP017_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM118.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM118-BiooBarcode15_ATGTCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM118-BiooBarcode15_ATGTCA_R1.fastq.gz > $LOGDIR/OM118_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM236.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM236-BiooBarcode21_GTTTCG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM236-BiooBarcode21_GTTTCG_R2.fastq.gz > $LOGDIR/OM236_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB017.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB017-BiooBarcode_34_CATGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB017-BiooBarcode_34_CATGGC_R2.fastq.gz > $LOGDIR/BB017_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM018.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM018-BiooBarcode6_CTTGTA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM018-BiooBarcode6_CTTGTA_R2.fastq.gz > $LOGDIR/OM018_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP034.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP034-BiooBarcode_24_GGTAGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP034-BiooBarcode_24_GGTAGC_R2.fastq.gz > $LOGDIR/KP034_align_log.txt
