cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM317.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM317-BiooBarcode41_GACGAC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM317-BiooBarcode41_GACGAC_R1.fastq.gz 
 > $LOGDIR/OM317_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM099.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-099_TGACCA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-099_TGACCA_R2.fastq.gz 
 > $LOGDIR/OM099_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM092.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM092-BiooBarcode13_AGTCAA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM092-BiooBarcode13_AGTCAA_R2.fastq.gz 
 > $LOGDIR/OM092_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM310.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM310-BiooBarcode38_CTAGCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM310-BiooBarcode38_CTAGCT_R1.fastq.gz 
 > $LOGDIR/OM310_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM313.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM313-BiooBarcode39_CTATAC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM313-BiooBarcode39_CTATAC_R2.fastq.gz 
 > $LOGDIR/OM313_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM271.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM271-BiooBarcode25_ACTGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM271-BiooBarcode25_ACTGAT_R2.fastq.gz 
 > $LOGDIR/OM271_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM015.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM015-BiooBarcode5_CAGATC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM015-BiooBarcode5_CAGATC_R1.fastq.gz 
 > $LOGDIR/OM015_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM012.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM012-BiooBarcode1_CGATGT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM012-BiooBarcode1_CGATGT_R2.fastq.gz 
 > $LOGDIR/OM012_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM273.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM273-BiooBarcode26_ATGAGC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM273-BiooBarcode26_ATGAGC_R1.fastq.gz 
 > $LOGDIR/OM273_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM270.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM270-BiooBarcode16_CCGTCC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM270-BiooBarcode16_CCGTCC_R2.fastq.gz 
 > $LOGDIR/OM270_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM317.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM317-BiooBarcode41_GACGAC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM317-BiooBarcode41_GACGAC_R1.fastq.gz > $LOGDIR/OM317_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM099.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-099_TGACCA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-099_TGACCA_R2.fastq.gz > $LOGDIR/OM099_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM092.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM092-BiooBarcode13_AGTCAA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM092-BiooBarcode13_AGTCAA_R2.fastq.gz > $LOGDIR/OM092_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM310.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM310-BiooBarcode38_CTAGCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM310-BiooBarcode38_CTAGCT_R1.fastq.gz > $LOGDIR/OM310_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM313.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM313-BiooBarcode39_CTATAC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM313-BiooBarcode39_CTATAC_R2.fastq.gz > $LOGDIR/OM313_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM271.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM271-BiooBarcode25_ACTGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM271-BiooBarcode25_ACTGAT_R2.fastq.gz > $LOGDIR/OM271_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM015.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM015-BiooBarcode5_CAGATC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM015-BiooBarcode5_CAGATC_R1.fastq.gz > $LOGDIR/OM015_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM012.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM012-BiooBarcode1_CGATGT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM012-BiooBarcode1_CGATGT_R2.fastq.gz > $LOGDIR/OM012_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM273.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM273-BiooBarcode26_ATGAGC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM273-BiooBarcode26_ATGAGC_R1.fastq.gz > $LOGDIR/OM273_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM270.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM270-BiooBarcode16_CCGTCC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM270-BiooBarcode16_CCGTCC_R2.fastq.gz > $LOGDIR/OM270_align_log.txt
