cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM245.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM245-BiooBarcode23_GAGTGG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM245-BiooBarcode23_GAGTGG_R2.fastq.gz 
 > $LOGDIR/OM245_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM244.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM244-BiooBarcode22_CGTACG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM244-BiooBarcode22_CGTACG_R2.fastq.gz 
 > $LOGDIR/OM244_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB016.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB016-BiooBarcode_33_CAGGCG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB016-BiooBarcode_33_CAGGCG_R1.fastq.gz 
 > $LOGDIR/BB016_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM105.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-105_ACAGTG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-105_ACAGTG_R2.fastq.gz 
 > $LOGDIR/OM105_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM269.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM269-BiooBarcode24_GGTAGC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM269-BiooBarcode24_GGTAGC_R1.fastq.gz 
 > $LOGDIR/OM269_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM044.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM044-BiooBarcode8_TTAGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM044-BiooBarcode8_TTAGGC_R2.fastq.gz 
 > $LOGDIR/OM044_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM164.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM164-BiooBarcode18_GTCCGC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM164-BiooBarcode18_GTCCGC_R1.fastq.gz 
 > $LOGDIR/OM164_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM046.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM046-BiooBarcode9_ACTTGA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM046-BiooBarcode9_ACTTGA_R1.fastq.gz 
 > $LOGDIR/OM046_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM125.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-125_ATCACG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-125_ATCACG_R1.fastq.gz 
 > $LOGDIR/OM125_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM115.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM115-BiooBarcode14_AGTTCC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM115-BiooBarcode14_AGTTCC_R2.fastq.gz 
 > $LOGDIR/OM115_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM245.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM245-BiooBarcode23_GAGTGG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM245-BiooBarcode23_GAGTGG_R2.fastq.gz > $LOGDIR/OM245_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM244.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM244-BiooBarcode22_CGTACG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM244-BiooBarcode22_CGTACG_R2.fastq.gz > $LOGDIR/OM244_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB016.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB016-BiooBarcode_33_CAGGCG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB016-BiooBarcode_33_CAGGCG_R1.fastq.gz > $LOGDIR/BB016_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM105.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-105_ACAGTG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-105_ACAGTG_R2.fastq.gz > $LOGDIR/OM105_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM269.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM269-BiooBarcode24_GGTAGC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM269-BiooBarcode24_GGTAGC_R1.fastq.gz > $LOGDIR/OM269_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM044.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM044-BiooBarcode8_TTAGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM044-BiooBarcode8_TTAGGC_R2.fastq.gz > $LOGDIR/OM044_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM164.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM164-BiooBarcode18_GTCCGC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM164-BiooBarcode18_GTCCGC_R1.fastq.gz > $LOGDIR/OM164_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM046.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM046-BiooBarcode9_ACTTGA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM046-BiooBarcode9_ACTTGA_R1.fastq.gz > $LOGDIR/OM046_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM125.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-125_ATCACG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-125_ATCACG_R1.fastq.gz > $LOGDIR/OM125_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM115.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM115-BiooBarcode14_AGTTCC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM115-BiooBarcode14_AGTTCC_R2.fastq.gz > $LOGDIR/OM115_align_log.txt
