cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM296.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM296-BiooBarcode32_CACTCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM296-BiooBarcode32_CACTCA_R1.fastq.gz 
 > $LOGDIR/OM296_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP070.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP070-BiooBarcode_29_CAACTA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP070-BiooBarcode_29_CAACTA_R1.fastq.gz 
 > $LOGDIR/KP070_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM339.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM339-BiooBarcode43_TACAGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM339-BiooBarcode43_TACAGC_R2.fastq.gz 
 > $LOGDIR/OM339_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP067.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP067-BiooBarcode_27_ATTCCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP067-BiooBarcode_27_ATTCCT_R1.fastq.gz 
 > $LOGDIR/KP067_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM074.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM074-BiooBarcode10_GATCAG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM074-BiooBarcode10_GATCAG_R2.fastq.gz 
 > $LOGDIR/OM074_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB035.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB035-BiooBarcode_39_CTATAC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB035-BiooBarcode_39_CTATAC_R1.fastq.gz 
 > $LOGDIR/BB035_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM076.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM076-BiooBarcode11_TAGCTT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM076-BiooBarcode11_TAGCTT_R2.fastq.gz 
 > $LOGDIR/OM076_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB019.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB019-BiooBarcode_35_CATTTT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB019-BiooBarcode_35_CATTTT_R2.fastq.gz 
 > $LOGDIR/BB019_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM078.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM078-BiooBarcode12_GGCTAC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM078-BiooBarcode12_GGCTAC_R2.fastq.gz 
 > $LOGDIR/OM078_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM314.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM314-BiooBarcode40_CTCAGA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM314-BiooBarcode40_CTCAGA_R2.fastq.gz 
 > $LOGDIR/OM314_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM296.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM296-BiooBarcode32_CACTCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM296-BiooBarcode32_CACTCA_R1.fastq.gz > $LOGDIR/OM296_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP070.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP070-BiooBarcode_29_CAACTA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP070-BiooBarcode_29_CAACTA_R1.fastq.gz > $LOGDIR/KP070_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM339.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM339-BiooBarcode43_TACAGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM339-BiooBarcode43_TACAGC_R2.fastq.gz > $LOGDIR/OM339_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP067.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP067-BiooBarcode_27_ATTCCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP067-BiooBarcode_27_ATTCCT_R1.fastq.gz > $LOGDIR/KP067_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM074.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM074-BiooBarcode10_GATCAG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM074-BiooBarcode10_GATCAG_R2.fastq.gz > $LOGDIR/OM074_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB035.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB035-BiooBarcode_39_CTATAC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB035-BiooBarcode_39_CTATAC_R1.fastq.gz > $LOGDIR/BB035_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM076.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM076-BiooBarcode11_TAGCTT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM076-BiooBarcode11_TAGCTT_R2.fastq.gz > $LOGDIR/OM076_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB019.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB019-BiooBarcode_35_CATTTT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB019-BiooBarcode_35_CATTTT_R2.fastq.gz > $LOGDIR/BB019_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM078.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM078-BiooBarcode12_GGCTAC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM078-BiooBarcode12_GGCTAC_R2.fastq.gz > $LOGDIR/OM078_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM314.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM314-BiooBarcode40_CTCAGA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM314-BiooBarcode40_CTCAGA_R2.fastq.gz > $LOGDIR/OM314_align_log.txt
