cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM284.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM284-BiooBarcode30_CACCGG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM284-BiooBarcode30_CACCGG_R1.fastq.gz 
 > $LOGDIR/OM284_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM283.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM283-BiooBarcode29_CAACTA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM283-BiooBarcode29_CAACTA_R1.fastq.gz 
 > $LOGDIR/OM283_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM282.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM282-BiooBarcode28_CAAAAG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM282-BiooBarcode28_CAAAAG_R1.fastq.gz 
 > $LOGDIR/OM282_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM312.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM312-BiooBarcode25_ACTGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM312-BiooBarcode25_ACTGAT_R2.fastq.gz 
 > $LOGDIR/OM312_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM141.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM141-BiooBarcode10_GATCAG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM141-BiooBarcode10_GATCAG_R2.fastq.gz 
 > $LOGDIR/OM141_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM142.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM142-BiooBarcode16_CCGTCC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM142-BiooBarcode16_CCGTCC_R1.fastq.gz 
 > $LOGDIR/OM142_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM143.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM143-BiooBarcode17_GTAGAG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM143-BiooBarcode17_GTAGAG_R1.fastq.gz 
 > $LOGDIR/OM143_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB023.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB023-BiooBarcode_37_CGGAAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB023-BiooBarcode_37_CGGAAT_R1.fastq.gz 
 > $LOGDIR/BB023_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB021.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB021-BiooBarcode_36_CCAACA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB021-BiooBarcode_36_CCAACA_R1.fastq.gz 
 > $LOGDIR/BB021_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM146.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-146_TTAGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-146_TTAGGC_R2.fastq.gz 
 > $LOGDIR/OM146_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM284.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM284-BiooBarcode30_CACCGG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM284-BiooBarcode30_CACCGG_R1.fastq.gz > $LOGDIR/OM284_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM283.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM283-BiooBarcode29_CAACTA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM283-BiooBarcode29_CAACTA_R1.fastq.gz > $LOGDIR/OM283_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM282.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM282-BiooBarcode28_CAAAAG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM282-BiooBarcode28_CAAAAG_R1.fastq.gz > $LOGDIR/OM282_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM312.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM312-BiooBarcode25_ACTGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM312-BiooBarcode25_ACTGAT_R2.fastq.gz > $LOGDIR/OM312_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM141.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM141-BiooBarcode10_GATCAG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM141-BiooBarcode10_GATCAG_R2.fastq.gz > $LOGDIR/OM141_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM142.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM142-BiooBarcode16_CCGTCC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM142-BiooBarcode16_CCGTCC_R1.fastq.gz > $LOGDIR/OM142_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM143.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM143-BiooBarcode17_GTAGAG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM143-BiooBarcode17_GTAGAG_R1.fastq.gz > $LOGDIR/OM143_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB023.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB023-BiooBarcode_37_CGGAAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB023-BiooBarcode_37_CGGAAT_R1.fastq.gz > $LOGDIR/BB023_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB021.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB021-BiooBarcode_36_CCAACA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB021-BiooBarcode_36_CCAACA_R1.fastq.gz > $LOGDIR/BB021_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM146.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-146_TTAGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-146_TTAGGC_R2.fastq.gz > $LOGDIR/OM146_align_log.txt
