cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM304.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM304-BiooBarcode36_CCAACA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM304-BiooBarcode36_CCAACA_R1.fastq.gz 
 > $LOGDIR/OM304_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM305.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM305-BiooBarcode37_CGGAAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM305-BiooBarcode37_CGGAAT_R1.fastq.gz 
 > $LOGDIR/OM305_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM302.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM302-BiooBarcode34_CATGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM302-BiooBarcode34_CATGGC_R2.fastq.gz 
 > $LOGDIR/OM302_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM303.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM303-BiooBarcode35_CATTTT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM303-BiooBarcode35_CATTTT_R2.fastq.gz 
 > $LOGDIR/OM303_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM300.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM300-BiooBarcode4_GCCAAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM300-BiooBarcode4_GCCAAT_R2.fastq.gz 
 > $LOGDIR/OM300_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM208.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM208-BiooBarcode19_GTGAAA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM208-BiooBarcode19_GTGAAA_R2.fastq.gz 
 > $LOGDIR/OM208_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB014.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB014-BiooBarcode_32_CACTCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB014-BiooBarcode_32_CACTCA_R1.fastq.gz 
 > $LOGDIR/BB014_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM124.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-124_CTTGTA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-124_CTTGTA_R1.fastq.gz 
 > $LOGDIR/OM124_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM275.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM275-BiooBarcode27_ATTCCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM275-BiooBarcode27_ATTCCT_R1.fastq.gz 
 > $LOGDIR/OM275_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM108.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-108_GCCAAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-108_GCCAAT_R1.fastq.gz 
 > $LOGDIR/OM108_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM304.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM304-BiooBarcode36_CCAACA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM304-BiooBarcode36_CCAACA_R1.fastq.gz > $LOGDIR/OM304_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM305.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM305-BiooBarcode37_CGGAAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM305-BiooBarcode37_CGGAAT_R1.fastq.gz > $LOGDIR/OM305_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM302.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM302-BiooBarcode34_CATGGC_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM302-BiooBarcode34_CATGGC_R2.fastq.gz > $LOGDIR/OM302_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM303.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM303-BiooBarcode35_CATTTT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM303-BiooBarcode35_CATTTT_R2.fastq.gz > $LOGDIR/OM303_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM300.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM300-BiooBarcode4_GCCAAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM300-BiooBarcode4_GCCAAT_R2.fastq.gz > $LOGDIR/OM300_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM208.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM208-BiooBarcode19_GTGAAA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM208-BiooBarcode19_GTGAAA_R2.fastq.gz > $LOGDIR/OM208_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB014.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB014-BiooBarcode_32_CACTCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB014-BiooBarcode_32_CACTCA_R1.fastq.gz > $LOGDIR/BB014_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM124.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-124_CTTGTA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-124_CTTGTA_R1.fastq.gz > $LOGDIR/OM124_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM275.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM275-BiooBarcode27_ATTCCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM275-BiooBarcode27_ATTCCT_R1.fastq.gz > $LOGDIR/OM275_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM108.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-108_GCCAAT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-108_GCCAAT_R1.fastq.gz > $LOGDIR/OM108_align_log.txt
