cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM192.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM192-BiooBarcode2_TGACCA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM192-BiooBarcode2_TGACCA_R2.fastq.gz 
 > $LOGDIR/OM192_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB034.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB034-BiooBarcode_38_CTAGCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB034-BiooBarcode_38_CTAGCT_R1.fastq.gz 
 > $LOGDIR/BB034_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM114.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-114_CAGATC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-114_CAGATC_R1.fastq.gz 
 > $LOGDIR/OM114_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP053.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP053-BiooBarcode_25_ACTGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP053-BiooBarcode_25_ACTGAT_R2.fastq.gz 
 > $LOGDIR/KP053_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM299.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM299-BiooBarcode33_CAGGCG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM299-BiooBarcode33_CAGGCG_R2.fastq.gz 
 > $LOGDIR/OM299_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM355.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM355-BiooBarcode48_TCGGCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM355-BiooBarcode48_TCGGCA_R1.fastq.gz 
 > $LOGDIR/OM355_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM354.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM354-BiooBarcode47_TCGAAG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM354-BiooBarcode47_TCGAAG_R1.fastq.gz 
 > $LOGDIR/OM354_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM220.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM220-BiooBarcode20_GTGGCC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM220-BiooBarcode20_GTGGCC_R1.fastq.gz 
 > $LOGDIR/OM220_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM214.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM214-BiooBarcode3_ACAGTG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM214-BiooBarcode3_ACAGTG_R1.fastq.gz 
 > $LOGDIR/OM214_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM292.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM292-BiooBarcode31_CACGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM292-BiooBarcode31_CACGAT_R2.fastq.gz 
 > $LOGDIR/OM292_align_log.txtcd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM192.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM192-BiooBarcode2_TGACCA_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM192-BiooBarcode2_TGACCA_R2.fastq.gz > $LOGDIR/OM192_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o BB034.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/BB034-BiooBarcode_38_CTAGCT_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/BB034-BiooBarcode_38_CTAGCT_R1.fastq.gz > $LOGDIR/BB034_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM114.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM-114_CAGATC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM-114_CAGATC_R1.fastq.gz > $LOGDIR/OM114_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o KP053.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/KP053-BiooBarcode_25_ACTGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/KP053-BiooBarcode_25_ACTGAT_R2.fastq.gz > $LOGDIR/KP053_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM299.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM299-BiooBarcode33_CAGGCG_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM299-BiooBarcode33_CAGGCG_R2.fastq.gz > $LOGDIR/OM299_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM355.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM355-BiooBarcode48_TCGGCA_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM355-BiooBarcode48_TCGGCA_R1.fastq.gz > $LOGDIR/OM355_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM354.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM354-BiooBarcode47_TCGAAG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM354-BiooBarcode47_TCGAAG_R1.fastq.gz > $LOGDIR/OM354_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM220.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM220-BiooBarcode20_GTGGCC_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM220-BiooBarcode20_GTGGCC_R1.fastq.gz > $LOGDIR/OM220_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM214.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM214-BiooBarcode3_ACAGTG_R2.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM214-BiooBarcode3_ACAGTG_R1.fastq.gz > $LOGDIR/OM214_align_log.txt
cd /home/vdp5/data/cambodia_samples/sequences_sam
stampy.py -o OM292.sam -f sam --substitutionrate=0.05 -g /home/vdp5/data/salvador_vivax/salvador.fasta -h /home/vdp5/data/salvador_vivax/salvador.fasta -M /home/vdp5/data/cambodia_samples/sequences_gz/OM292-BiooBarcode31_CACGAT_R1.fastq.gz /home/vdp5/data/cambodia_samples/sequences_gz/OM292-BiooBarcode31_CACGAT_R2.fastq.gz > $LOGDIR/OM292_align_log.txt
